<?php

namespace AppBundle\Repository;

/**
 * TwittsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TwittsRepository extends \Doctrine\ORM\EntityRepository
{
}
